server:
  port: 8084
  
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/FoodMenuService
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true 
    
  application:
    name: FOODMENU-SERVICE
    
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka