server:
  port: 8085
  
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true 
    
  application:
    name: ORDER-SERVICE
    
